# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Platform test"

on:
  pull_request:
  push:
    branches:
      - "2.0.x"

jobs:
  tests:
    name: "Platform test"
    runs-on: "ubuntu-latest"
    env:
      MYSQL_HOST: '127.0.0.1'
      PGSQL_HOST: '127.0.0.1'
      MSSQL_HOST: '127.0.0.1'

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        update-packages:
          - ""
        include:
          - php-version: "8.1"
            update-packages: doctrine/orm:^3.0 doctrine/dbal:^4.0 carbonphp/carbon-doctrine-types:^3 gedmo/doctrine-extensions:^3
          - php-version: "8.2"
            update-packages: doctrine/orm:^3.0 doctrine/dbal:^4.0 carbonphp/carbon-doctrine-types:^3 gedmo/doctrine-extensions:^3
          - php-version: "8.3"
            update-packages: doctrine/orm:^3.0 doctrine/dbal:^4.0 carbonphp/carbon-doctrine-types:^3 gedmo/doctrine-extensions:^3
          - php-version: "8.4"
            update-packages: doctrine/orm:^3.0 doctrine/dbal:^4.0 carbonphp/carbon-doctrine-types:^3 gedmo/doctrine-extensions:^3

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          extensions: pdo, mysqli, pgsql, pdo_mysql, pdo_pgsql, pdo_sqlite, mongodb

      - name: "Allow installing on PHP 8.4"
        if: matrix.php-version == '8.4'
        run: "composer config platform.php 8.3.99"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Update packages"
        if: ${{ matrix.update-packages != '' }}
        run: composer require --dev ${{ matrix.update-packages }} -W

      - name: "Run platform matrix test"
        run: vendor/bin/phpunit --group=platform

    services:
      postgres:
        image: "postgres:latest"
        env:
          POSTGRES_PASSWORD: "secret"
          POSTGRES_USER: root
          POSTGRES_DB: foo
        ports:
          - "5432:5432"

      mysql:
        image: "mysql:latest"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: foo
        ports:
          - "3306:3306"

      mssql:
        image: mcr.microsoft.com/mssql/server:latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: 'Secret.123'
          MSSQL_PID: Developer
        ports:
          - 1433:1433
